name: CI Tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r testing_requirements.txt
    - name: Run the unit tests
      run: |
        coverage run -p -m unittest discover -b tests
    - name: Run the Python linter
      run: |
        prospector
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python-version }}
        path: .coverage.*
        include-hidden-files: true

  upload-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        check-latest: true
    - name: Download coverage artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Combine coverage files
      run: |
        python -m pip install -r testing_requirements.txt
        find artifacts -name ".coverage.*" -exec mv {} . \;
        coverage combine
        coverage xml
        coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
