name: CI Tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ['3.9', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ startsWith(matrix.os, 'windows') && matrix.py || format('pypy-{0}', matrix.py) }}
    - name: Install dependencies
      run: |
        python -m pip install ".[test]"
    - name: Run the unit tests
      shell: bash
      run: |
        for attempt in 1 2 3; do
          if coverage run -p -m unittest discover -b tests; then
            exit 0
          fi
          sleep 2
        done
        exit 1
    - name: Run the Python linter
      run: |
        prospector
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.python-version }}
        path: .coverage.*
        include-hidden-files: true

  upload-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        check-latest: true
    - name: Download coverage artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Combine coverage files
      run: |
        python -m pip install ".[test]"
        find artifacts -name ".coverage.*" -exec mv {} . \;
        coverage combine
        coverage xml
        coverage report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3'
        check-latest: true
    - name: Build documentation
      run: |
        python -m pip install ".[docs]"
        sphinx-build -W -b html docs docs/_build/html
        sphinx-build -W -b doctest docs docs/_build/doctest
        sphinx-build -W -b linkcheck docs docs/_build/linkcheck
